### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by darragh-hayes** [nearform/nscale-kernel#83]
Peter told me to pull down the latest code from today and to test it. When deploying to any target I get this:

ERROR: {"request":"revision deploy","responseType":"stderr","level":"error"}

And the server logs show:

{"name":"nfd-kernel","hostname":"ip-172-30-0-158","pid":11873,"level":30,"msg":"rcv: revision deploy","time":"2015-02-23T15:43:04.249Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-158","pid":11873,"level":30,"systemId":"62999e58-66a0-4e50-a870-f2673acf6c79","revisionId":"e5395efff25874cab542dcafc89b9bd4ddb9e378","environment":"development","msg":"deploy revision","time":"2015-02-23T15:43:04.295Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-158","pid":11873,"level":30,"system":"sudc","msg":"analyze system","time":"2015-02-23T15:43:04.303Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-158","pid":11873,"level":30,"systemId":"62999e58-66a0-4e50-a870-f2673acf6c79","target":"development","msg":"get deployed system","time":"2015-02-23T15:43:04.340Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-158","pid":11873,"level":30,"msg":"get head system: 62999e58-66a0-4e50-a870-f2673acf6c79","time":"2015-02-23T15:43:04.341Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-158","pid":11873,"level":30,"msg":"running analysis against deployed system","time":"2015-02-23T15:43:04.348Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-158","pid":11873,"level":30,"msg":"analysis complete","time":"2015-02-23T15:43:04.353Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-158","pid":11873,"level":50,"msg":"could not determine id","time":"2015-02-23T15:43:04.353Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-158","pid":11873,"level":30,"msg":"rsp: deploy system [object Object] sudc latest development","time":"2015-02-23T15:43:04.353Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-158","pid":11873,"level":30,"msg":"could not determine id","time":"2015-02-23T15:43:04.354Z","v":0}
{"name":"nfd-kernel","hostname":"ip-172-30-0-158","pid":11873,"level":30,"msg":"stderr: undefined","time":"2015-02-23T15:43:04.354Z","v":0}

**Comment by mcollina** [comment]
It is working fine here. How are you getting this error?

**Comment by mcollina** [comment]
If you are using 0.14.9 from NPM and not the current branch, you might get problems. I just released 0.14.10.

**Comment by darragh-hayes** [comment]
I was pulling all the source down and inking it together manually. I'll
give it a go with 0.14.10

**Comment by darragh-hayes** [comment]
Issue has been patched and tested! Thanks
