### ISSUE TITLE
Unable to abbreviate target when building

### ISSUE THREAD

**Issue by darragh-hayes** [nearform/nscale-kernel#87]
I can run 

```nscale system compile sudc latest dev```

which works perfectly but if I do this:

```nscale container buildall sudc latest dev```

I just get ```--> building all containers for sudc revision latest target dev```
and nothing happens.

the buildall command currently must take the target name in full

**Comment by mcollina** [comment]
I forgot to use https://github.com/nearform/nscale-kernel/blob/master/lib/api.js#L242 to fetch the targets in build and buildall, would you mind adding the support this there and send a PR?

**Comment by darragh-hayes** [comment]
Done
