### ISSUE TITLE
default config.json file causing issues in v0.15-pre3

### ISSUE THREAD

**Issue by darragh-hayes** [nearform/nscale-kernel#97]
using v0.15-pre3 the `~/.nscale/config/config.json` file looks like this:

```
{
  "kernel": {
    "port": "8010",
    "root": "/home/dara/.nscale",
    "user": "YOUR_USERNAME",
    "identityFile": "YOUR_SSH_KEY_FILE",
    "region": "AWS_ONLY_YOUR_AWS_REGION",
    "accessKeyId": "AWS_ONLY_YOUR_AWS_ACCESS_KEY",
    "secretAccessKey": "AWS_ONLY_YOUR_AWS_SECRET_ACCESS_KEY"
  },
  "api": {
  },
  "web": {
  },
  "modules": {
    "protocol": {
      "require": "nscale-protocol",
      "specific": {
      }
    },
    "authorization": {
      "require": "nscale-noauth",
      "specific": {
        "credentialsPath": "/home/dara/.nscale/data"
      }
    }
  }
}
```

this causes issues in aws because even if I have my aws specific configurations specified in a system config.js file, I get errors because nscale is looking for a keyfile called "YOUR_SSH_KEY_FILE." can we change it so the default file does not include these?

**Comment by mcollina** [comment]
This is already updated and fixed, but not released.
Il giorno gio 19 mar 2015 alle 16:46 Darragh Hayes <notifications@github.com>
ha scritto:
